spring:
  application:
    name: project
  datasource:
      url: ${BD_URL}
      username: ${BD_USER}
      password: ${BD_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

server:
  port: 8081
